# Generated by Django 3.1.1 on 2020-10-09 06:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='telephone1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number2', max_length=128, region=None),
        ),
    ]
