# Generated by Django 3.1.2 on 2020-10-09 10:22

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201009_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.IntegerField(default=myapp.models.from_100, primary_key=True, serialize=False),
        ),
    ]
