# Generated by Django 3.1.2 on 2020-10-09 10:55

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201009_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.IntegerField(default=myapp.models.from_400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(default=myapp.models.from_category_10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.IntegerField(default=myapp.models.from_country_10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_id',
            field=models.IntegerField(default=myapp.models.from_1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(default=myapp.models.from_300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='financetype',
            name='financetype_id',
            field=models.IntegerField(default=myapp.models.from_finance_10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='Lawyer_id',
            field=models.IntegerField(default=myapp.models.from_200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_id',
            field=models.IntegerField(default=myapp.models.from_10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=myapp.models.from_user_100, primary_key=True, serialize=False),
        ),
    ]
