# Generated by Django 3.1.2 on 2020-10-09 11:03

import django.core.validators
from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201009_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_id',
            field=models.IntegerField(default=myapp.models.from_10, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
