# Generated by Django 3.1.2 on 2020-10-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201009_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='person_id',
            field=models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='person_id',
            field=models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_id',
            field=models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
    ]
