# Generated by Django 3.1.2 on 2020-10-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20201009_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category_id',
            field=models.OneToOneField(blank=True, db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='case',
            name='country_id',
            field=models.OneToOneField(blank=True, db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.country'),
        ),
        migrations.AlterField(
            model_name='case',
            name='financetype_id',
            field=models.OneToOneField(blank=True, db_column='financetype_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.financetype'),
        ),
        migrations.AlterField(
            model_name='case',
            name='lawyer_id',
            field=models.OneToOneField(blank=True, db_column='lawyer_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.lawyer'),
        ),
    ]
