# Generated by Django 3.1.2 on 2020-10-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20201009_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('user', 'USER')], default='admin', max_length=100),
        ),
    ]
