# Generated by Django 3.1.2 on 2020-10-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20201009_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='customer_lost_amounttxt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='customer_message',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='customer_played_where',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='customer_wants_financing',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='is_customer_already',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='agree_condition',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_de',
            field=models.CharField(choices=[('osterreich', 'Österreich'), ('deutschland', 'Deutschland'), ('schweiz', 'Schweiz')], max_length=255),
        ),
    ]
